### ISSUE TITLE
Search needs fixing

### ISSUE THREAD

**Issue by iamlasse** [mtr-cherish/cherish#138]
Search is currently not working, is not integrated with filter, and initiative images disappear when searching.

**Comment by iamlasse** [comment]
getInitiativeImage seems to return nothing when in a search

**Comment by jeffshaver** [comment]
I believe I found the issue. It is because when searching, we aren't returning a real mongo cursor. we are returning an object. The reason this is a problem is because getInitiativeImage is a collection helper (which it should be) and if you return something that isn't a cursor, we don't get to use the collection helpers...

`/client/templates/initiatives/initiatives.js` is the file that needs to be fixed.

**Comment by jeffshaver** [comment]
The easiest way to get around this is just to avoid the search source package altogether. It doesn't allow returning a reactive cursor. I think we should find a different search package or just implement on our own (not difficult).
