### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by ralphking** [mtr-cherish/cherish#57]
At the moment https://github.com/mtr-cherish/cherish/blob/master/lib/collections/initiatives.js#L24-L30 is redundant for filtering as we are hard-coding categories see: (https://github.com/mtr-cherish/cherish/blob/master/lib/collections/initiatives.js#L19).

Are we going to allow users to create new categories when they start an initiative (I suppose that's more like 'tags'), or are we going to let them select from a pre-defined list? If the latter, unless we still want to have category routes (/category/open-source) which currently seem to be broken, we can just remove that code and clean up.

EDIT - Reason category pages are currently broken is due to the search stuff not taking them into account. https://github.com/mtr-cherish/cherish/blob/master/client/templates/initiatives/initiatives.js#L1-L19

**Comment by jeffshaver** [comment]
It doesn't seem like they should be able to make up their own categories since they are supposed to be for "good" things like charity/open-source. However, it does seem like it would be a good thing to add tags which are user-creatable. Like it may make sense to try and fund a charity. But what kind of charity? Cancer? Some other disease? It seems like tags would solve the ambiguity there.

**Comment by ralphking** [comment]
So perhaps, categories are always hardcoded, but we could extrapolate away the routing + logic for category pages and create a tagging system instead. That way the search wouldn't interfere with it. Or at least add it into the Roadmap

**Comment by trustieee** [comment]
Correct, Categories are set as part of the Cherish platform. Tags (a possible feature) would be user-entered and used for filtering at some point.
